// Fits every class of the transformation hierarchy to correspondences generated by a known homography and
// prints the residual of each fit, then decomposes the homography (chapter 1).
//
//   ./01_hierarchy [perspective]      perspective: magnitude of the bottom-row entries (default 1e-3)

#include <cstdio>
#include <cstdlib>
#include <random>

#include "mvg/projective.hpp"

int main(int argc, char** argv) {
    const double perspective = argc > 1 ? std::atof(argv[1]) : 1e-3;

    Eigen::Matrix3d H = mvg::make_similarity(1.1, 0.2, 15.0, -5.0);
    Eigen::Matrix3d shear = Eigen::Matrix3d::Identity();
    shear(0, 1) = 0.25;
    H = H * shear;
    H(2, 0) = perspective;
    H(2, 1) = -0.5 * perspective;

    std::mt19937 rng(0);
    std::uniform_real_distribution<double> u(-200.0, 200.0);
    std::normal_distribution<double> noise(0.0, 0.5);
    mvg::Points2 x(2, 100);
    for (int j = 0; j < x.cols(); ++j) x.col(j) << u(rng), u(rng);
    mvg::Points2 xp = mvg::apply_homography(H, x);
    for (int j = 0; j < xp.cols(); ++j) xp.col(j) += Eigen::Vector2d(noise(rng), noise(rng));

    std::printf("true class: %s\n", mvg::to_string(mvg::classify_transform(H)).c_str());
    std::printf("%-12s  %s\n", "model", "rms transfer error [px]");
    for (auto c : {mvg::TransformClass::Translation, mvg::TransformClass::Euclidean,
                   mvg::TransformClass::Similarity, mvg::TransformClass::Affine}) {
        const Eigen::Matrix3d Hc = mvg::fit_transform(c, x, xp);
        std::printf("%-12s  %.3f\n", mvg::to_string(c).c_str(), mvg::rms_transfer_error(Hc, x, xp));
    }

    const auto dec = mvg::decompose_projective(H);
    std::printf("decomposition: s = %.4f, angle = %.4f rad, v = (%.2e, %.2e)\n", dec.scale, dec.angle,
                dec.projective(2, 0), dec.projective(2, 1));
    return 0;
}
